version: '3'

services:
    db:
        image: mariadb:10.5.5
        ports:
            - 3306
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: doctrine-test
            MYSQL_USER: test
            MYSQL_PASSWORD: s3cr37
