version: '3'

services:
    db:
        image: postgres:13-alpine
        ports:
            - 5432
        environment:
            POSTGRES_DB: doctrine-test
            POSTGRES_USER: test
            POSTGRES_PASSWORD: s3cr37
